Updated version constraints (#59)
* Updated version constraints

The `aws = ~> 2.0` causes error in Terraform 0.13:

```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints >= 3.0.*, >= 2.0.*, >=
2.0.*, >= 2.0.*, >= 2.0.*, >= 2.0.*, < 4.0.*, ~> 2.0, ~> 2.0, ~> 2.0, ~> 2.0,
~> 2.0, ~> 2.0, >= 2.0.*, < 4.0.*, >= 3.0.*, >= 2.0.*, >= 2.0.*, >= 2.0.*
```

* Updated README.md

* Update versions.tf

* Updated README.md

Co-authored-by: actions-bot <58130806+actions-bot@users.noreply.github.com>